// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJB7Q5W68wM_R-ajOD6GIcRvxancWPqHE',
    appId: '1:919821444496:web:9ed6de0db9ff094029ff15',
    messagingSenderId: '919821444496',
    projectId: 'loginapp-f4cd8',
    authDomain: 'loginapp-f4cd8.firebaseapp.com',
    storageBucket: 'loginapp-f4cd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS1cmZrLJ2x34LLZHCJ4ztyN8n-FDiCWU',
    appId: '1:919821444496:android:451d131c36832bbd29ff15',
    messagingSenderId: '919821444496',
    projectId: 'loginapp-f4cd8',
    storageBucket: 'loginapp-f4cd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgPJbkA6vHEdBcVlWutWykUVUkSGSKlR0',
    appId: '1:919821444496:ios:53fde79c63844b4029ff15',
    messagingSenderId: '919821444496',
    projectId: 'loginapp-f4cd8',
    storageBucket: 'loginapp-f4cd8.appspot.com',
    iosClientId: '919821444496-j14r3f4qm16ami7o6igv8in718hgo6c7.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgPJbkA6vHEdBcVlWutWykUVUkSGSKlR0',
    appId: '1:919821444496:ios:2a3acde858f294d129ff15',
    messagingSenderId: '919821444496',
    projectId: 'loginapp-f4cd8',
    storageBucket: 'loginapp-f4cd8.appspot.com',
    iosClientId: '919821444496-bbmvlt7cr690em856vuv0c6uqifluc25.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationApp.RunnerTests',
  );
}
